version: '2'
services:
  ccdb-service:
    image: lnls/docker-ccdb-service-wildfly:1.2.6-1
    ports:
      - "8083:8080"
      - "9993:9990"
      - "8446:8443"
    container_name: ccdb-service
    depends_on:
      - ccdb-postgres
    dns:
        - 10.0.0.71
        - 10.0.0.72
    extra_hosts:
      - "sirius-rbac-auth.lnls.br:172.18.0.3"
      - "sirius-rbac.lnls.br:172.18.0.4"
      - "sirius-ns.lnls.br:172.18.0.6"
      - "sirius-cable.lnls.br:172.18.0.8"
    entrypoint: /wait-for-it.sh
    command: ccdb-postgres:5432 -- /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0
    networks:
      - postgres-ccdb

  ccdb-postgres:
    image: lnls/docker-ccdb-postgres:1.2.6-1
    ports:
      - "5435:5432"
    container_name: ccdb-postgres
    volumes:
      - ccdb-postgres-volume:/var/lib/postgresql/data
    networks:
      - postgres-ccdb
    env_file: env-vars/ccdb-postgres-vars.env

volumes:
  ccdb-postgres-volume:
    driver: local

networks:
  postgres-ccdb:
    external:
      name: dockerrbaccomposed_postgres-rbac
